### PR TITLE
[ISSUE #23] Support for creating multiple brokerClusters with differe…

### PR DESCRIPTION
**Pull request by zhihui921016**
…nt names

### CODE REVIEW

**Comment by zhihui921016** [comment]
> The original design principle of the `size` field of the CRD Broker means how many broker groups the cluster has. By broker groups, it means one master broker and several replica brokers( could be zero). A broker cluster means several broker groups with the same name prefix. If you want to broke that rule and allow multiple broker cluster exists with different names. I am not sure that in the broker scale up process, whether the operator will normally transmit the metadata from user-defined source broker pod to the new broker, could you please help checked the influence on the scale up process?
> 
> Besides, I think it is important to allow different broker cluster exists with different name prefix. To do that we have to clear the related concepts(the relationship of broker group, broker cluster, master, replica, etc.) and make the code consistent with that.
> Thank you very much for your contribution!

**Comment by zhihui921016** [comment]
@liuruiyiyang When deploying a broekr cluster, scalePodName needs to be prefixed with the broker cluster name. For example, if the name of broker is ‘broker’，the scalePodName is ‘broker-0-master-0’, if the name of broker is ‘cluster’, the scalePodName should be ‘cluster-0-master-0’

**Comment by zhihui921016** [comment]
@liuruiyiyang In addition, I have tested that the broker cluster can be scaled up normally before submission

**Comment by liuruiyiyang** [comment]
LGTM

**Pull request merged**
