### PR TITLE
[ISSUE 38] Add nodeAffinity for nameService pod

### PR DESCRIPTION
**Pull request by shendongsd**

### CODE REVIEW

**Review by caigy — APPROVED** [review]

**Comment by caigy** [comment]
@shendongsd Is there an issue related to this PR?

**Comment by shendongsd** [comment]
> @shendongsd Is there an issue related to this PR? Would you also support `preferredDuringSchedulingIgnoredDuringExecution`, or why not?
the  issues/38  is related to this PR，i will  also support preferredDuringSchedulingIgnoredDuringExecution and improve and perfect this PR

**Comment by shendongsd** [comment]
> 1. I think abbreviations like `reqDurSchIgnDurExe` are not no clear, especially for new beginners of K8s. For example, 'req' is short for 'request' in most cases other than 'require'. I think it more clear to leave the full names defined in K8s.
> 2. Could you provide the reason to remove `go.mod`? I don't think this deletion is related to the issue.

1、I changed the variable name and restored "go.mod"

**Comment by AdheipSingh** [comment]
the user should be able to just mention the nodeAffinity in the CR, templating out each and every spec in the nodeAffinity, isn't a best practice in the operator. 
```
nodeAffinity:
   ----
   ----
```
this is only needed in the CR.

**Pull request closed without merging**
