### PR TITLE
[ISSUE #154] Support deployment on multi platform.

### LINKED ISSUE #154: Don't support deployment on ARM environment.
Now it only support to deploy on linux/amd64, don't support  deployment on multi platform, like arm.

### PR DESCRIPTION
**Pull request by shangjin92**
Support to build product on multi platform by using docker buildx, like arm.

### CODE REVIEW

**Review by caigy — CHANGES_REQUESTED** [review]
I ran `make docker-build IMG=apache/rocketmq-operator:test` on my Mac with docker client  20.10.23, but resulted in error. Please take a look~

```sh
docker buildx build --platform linux/amd64,linux/arm64 --push -t apache/rocketmq-operator:test .
[+] Building 0.0s (0/0)                                                                                               
ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
make: *** [docker-build] Error 1
```

**Comment by shangjin92** [comment]
> 

https://forums.docker.com/t/error-multiple-platforms-feature-is-currently-not-supported-for-docker-driver/124811/11

Please try `docker buildx create --name multiarch --driver docker-container --use`, it works for me.

**Comment by caigy** [comment]
> > 
> 
> https://forums.docker.com/t/error-multiple-platforms-feature-is-currently-not-supported-for-docker-driver/124811/11
> 
> Please try `docker buildx create --name multiarch --driver docker-container --use`, it works for me.

@shangjin92 Could you please modify makefile so that this command is supported?

**Comment by shangjin92** [comment]
> > > 
> > 
> > 
> > https://forums.docker.com/t/error-multiple-platforms-feature-is-currently-not-supported-for-docker-driver/124811/11
> > Please try `docker buildx create --name multiarch --driver docker-container --use`, it works for me.
> 
> @shangjin92 Could you please modify makefile so that this command is supported?

PTAL

**Comment by drivebyer** [comment]
nice feature, any progress?

**Review by caigy — APPROVED** [review]
LGTM

**Pull request merged**
