### PR TITLE
add pod anti affinity for broker

### PR DESCRIPTION
**Pull request by overstep123**

### CODE REVIEW

**Comment by zongtanghu** [comment]
Hi，this pr has some codes conflicts, can you resolve it in your local enviroments?

**Comment by overstep123** [comment]
> 

done

**Review by caigy — COMMENTED** [review]
IMO although it's good practice to deploy brokers on different node in production, a user may be just deploy brokers in one node just for dev or test purpose. It would be better to leave the choice to users.

**Comment by overstep123** [comment]
I just found out that it's possible to pass through affinity from broker.yaml to statefulset.yaml(this is only after I initiated the PR).  Although it is still difficult to set different affinities for master and replica respectively, it works fine in most cases.  So maybe this PR is no longer useful. I'll close it

**Pull request closed without merging**
